config/routes.rb
AiVoluntariado::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :users do
    get :delete, :on => :member
    
    resources :performances do 
      get :delete, :on => :member
    end

    resources :organizations_trackings do
      get :delete, :on => :member
      get :destroy_all, :on => :collection
    end
      
  end

  resources :roles do
    get :delete, :on => :member
  end

  resources :performances do 
    get :delete, :on => :member
  end

  resource :site, :only => [:show,:edit,:update]

  match '/monitoring' => "monitoring#index", :as => :monitoring

  resources :activists do

    member do 
      get :delete
      get :leave
      get :clear
      get :rejoin
      get :admin_request
      put :send_admin_request
    end

    resources :activists_collaborations do 
      get :delete, :on => :member
    end

    resources :notes do
      get :delete, :on => :member
    end

  end

  resources :campaignactions do
    get :delete, :on => :member
  end

  resources :custom_actions do
    get :delete, :on => :member
  end

  resources :campaigns do
    get :delete, :on => :member
    get :show_info, :on => :collection
  end

  resources :hr_schools do
    get :delete, :on => :member
    resources :notes do 
      get :delete, :on => :member
    end
  end

  resources :mail_template_collections

  resources :provinces

  resources :talks do
    get :delete, :on => :member
  end

  resources :interesteds do
    get :delete, :on => :member
    get :to_activist, :on => :member
    get :prepare_pdf, :on => :member
    put :send_pdf, :on => :member
    get :prepare_mail, :on => :member
    put :send_mail, :on => :member

    resources :interested_communications, :path => :communications do 
      get :delete, :on => :member
      resources :notes do
        get :delete, :on => :member    
      end
    end

  end

  # ROUTES FOR ORGANIZATIONS

  resources :autonomies do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :autonomic_teams do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :committees do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  resources :countries do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
  end

  resources :local_organizations do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :se_teams do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  #ROUTES FOR EVENT RECORDS
  EventRecord.child_classes.prepend('EventRecord').each do |klass_name|
    resources klass_name.underscore.pluralize, :controller => 'event_records', :defaults => (klass_name != 'EventRecord' ? {:type => klass_name}:{}) do 
      get :delete, :on => :member    
      resources :notes do
        get :delete, :on => :member    
      end
    end
  end if EventRecord.table_exists?

  #ROUTES FOR ALERTS

  resources :alerts do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member    
    end
  end

  # Routes for AJAX requests
  match '/stages_for_performances'        => "performances#stages_for_performances", :as => :stages_for_performances
  match '/organizations_for_hr_schools'   => "hr_schools#organizations_for",         :as => :organizations_for_hr_schools
  match '/organizations_for_search'       => "search#organizations_for",             :as => :organizations_for_search
  match '/autonomic_teams_for_search'     => "search#autonomic_teams_for",           :as => :autonomic_teams_for_search
  match '/collaboration_types_for_search' => "search#collaboration_types_for",       :as => :collaboration_types_for_search
  match '/autonomic_teams_for_autonomy'   => "autonomies#autonomic_teams_for",       :as => :autonomic_teams_for_autonomy
  
  # Routes for auto_complete
  #TODO: simplify these routes
  match '/auto_complete/talks_as_options_for_interesteds' => 'talks#talks_as_options_for_interesteds', :as => :talks_as_options_for_interesteds_talks
  match '/auto_complete/talks_as_options_for_search'      => 'talks#talks_as_options_for_search',      :as => :talks_as_options_for_search_talks

#  match '/auto_complete/local_organizations_as_options_for_activists_collaborations/:local_organization_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_local_organization_activists_collaborations
#  match '/auto_complete/committees_as_options_for_activists_collaborations/:committee_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_committee_activists_collaborations
#  match '/auto_complete/se_teams_as_options_for_activists_collaborations/:se_team_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_se_team_activists_collaborations
#  match '/auto_complete/countries_as_options_for_activists_collaborations/:country_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_country_activists_collaborations
#  match '/auto_complete/autonomies_as_options_for_activists_collaborations/:autonomy_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_autonomy_activists_collaborations

  #PUBLIC ROUTES

  # HHRR schools: localized actions
  scope "(:locale)" do
    match '/form_hr_schools'   => 'public#new_hr_school',  :as => :form_hr_schools
    ["new_hr_school", "create_hr_school", "confirm_hr_school", "list_hr_schools"].each do |action_name|
      match "public/#{action_name}" => "public##{action_name}"
    end
  end

  # Interesteds: non-localized actions
  match '/form_voluntariado' => 'public#new_interested', :as => :form_voluntariado
  ["new_interested", "create_interested", "confirm_interested", "different_residence_country"].each do |action_name|
    match "public/#{action_name}" => "public##{action_name}"
  end

  # Ajax request for forms
  match '/provinces_for_cps'              => "public#provinces_for", :as => :provinces_for_cps
  match '/cities_for_province'            => "public#cities_for",    :as => :cities_for_province
  match '/city_for_cp'                    => "public#cities_for",    :as => :city_for_cp
  match '/cp_for_city'                    => "public#cp_for",        :as => :cp_for_city

  # Other static routes
  match '/gen_alerts'        => 'alerts#generate',  :as => :gen_alerts
  match '/search'            => 'search#index',     :as => :search
  match '/admin'             => 'admin#index',      :as => :admin

  root :to => "activists#index"

  # Note: This route will make all actions in every controller accessible via GET requests.
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Uncommment only for route testing purposes
#  match ':controller(/:action(/:id))(.:format)' 

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  before_filter :search_what, :only => :index
  
  
  def index
    @items = []
    if params[:commit]
      @items = @klass.advanced_search(params, current_agent) || []
      @search_results_count = @items.count
    end

    respond_to do |format|
      format.html { 
        @items_per_page = params[:per_page]  || 30
        @items = @items.paginate(:page => params[:page], :per_page => @items_per_page) 
      }
      format.csv  { 
        @items = @klass.sort_for_csv(@items)
        csv_string = render_to_string :template => "search/index", :layout => nil           
        send_data csv_string, :type => "text/plain",  :filename => "resultado_busqueda.csv", :disposition => 'attachment'
      }
    end
  end
  
  def organizations_for
    if params[:organization_type] and ActivistsCollaboration.organization_types.include?(params[:organization_type])
      @organizations = ActivistsCollaboration.organizations_by_type( "Member" + params[:organization_type])
      render :template => 'search/organizations_id_for_search', :layout => nil
    else
      render :text => 'fail', :status => 404
    end
  end
    
  def autonomic_teams_for
    autonomy = params[:organization_id].nil? || params[:organization_id].empty? ? nil : Autonomy.find(params[:organization_id])
    render :partial => 'search/autonomic_teams_for_search', :layout => false, :locals => {:autonomy => autonomy}
  end

  private
  def search_what
    searcheable_klasses = [ "activists", "activists_collaborations", "hr_schools", "campaignactions", "custom_actions", "interesteds", "talks", 
                            "local_organizations", "se_teams", "countries", "autonomies", "committees", "alerts" ]
    unless searcheable_klasses.include?(params[:what])
      flash[:error] = t('search.none')
      render(:file => "#{Rails.root}/public/404.html", :status => 404)
    else
      @klass = params[:what].camelize.singularize.constantize
    end
  end
end

app/views/search/_activists_filters.html.erb
<table class="table_list" >
  <tr class="important_row">
    <td colspan="2"><%= t('activist.search.search_params') %></td>
  </tr>

  <tbody class="unhideable">
    <% Activist.unhideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'activist', :field_name => field_name } %>
    <% end %>

    <tr class="list_style_0">
      <td>
        <label><%= t('activerecord.attributes.activists_collaboration.activist_status_id') %>:</label>
      </td>
      <td>
        <%= select("activist", "activists_collaborations_activist_status_id_eq",
                    ActivistStatus.all.collect {|as| [as.name,as.id] },
                    { :selected => (( params[:activist] && params[:activist]['activist_status_id']) ? params[:activist]['activist_status_id'].to_i : ''),
                                  :include_blank => true }) %>
      </td>
    </tr>

    <tr class="list_style_1">
      <td>
        <label><%= Gx.t_attr('activist.with_active_collaborations') %></label>
      </td>
      <td>
        <% cur_selected_value = (params[:activist] ? params[:activist][:with_active_collaborations] : '' ) %>
        <%= select  "activist", "with_active_collaborations", [["", ""],["Si","1"],["No","0"] ], :selected => cur_selected_value %>
      </td>    
    </tr>

    <tr class="list_style_0">
      <td>
        <label><%= Gx.t_attr('activist.is_partner') %></label>
      </td>
      <td>
        <% cur_selected_value = (params[:activist] ? params[:activist][:is_partner] : '' ) %>
        <%= select  "activist", "is_partner", [["", ""],["Si","1"],["No","0"] ], :selected => cur_selected_value %>
      </td>    
    </tr>

  </tbody>

  <%= render :partial => 'show_more_row' %>

  <tbody id="activist_extra_fields" class="hideable" style="display: none;">
    <% Activist.hideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'activist', :field_name => field_name } %>
    <% end %>
  </tbody>

  <tr class="important_row hideable" style="display: none;">
    <td colspan="2"><%= t('activist.search.collaborations_params') %></td>
  </tr>

  <tr class="list_style_0 hideable" style="display: none;">
    <td>
      <label><%= t('role.stage_type') %>:</label>
    </td>
    <td>
      <% organization_type_param  = (params[:activist] ? params[:activist][:activists_collaborations_organization_type_eq] : '') %>
      <% organization_type_values = [[ '', '']] + ActivistsCollaboration.organization_types.collect{ |o| [ Gx.t_attr("activists_collaboration.#{ o.underscore }"), o ] } %>
      <%= select "activist", "activists_collaborations_organization_type_eq", organization_type_values, :selected => organization_type_param %>
      <% content_for(:head){ javascript_tag "addAutocompleteInputCallback('activist_activists_collaborations_organization_type_eq', '#{organizations_for_search_path}', 'organization_type', 'activist_activists_collaborations_organization_id_eq');" } %>
    </td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.organization_id') %>:</label>
    </td>
    <td>
      <% organization_id_param  = (params[:activist] ? params[:activist][:activists_collaborations_organization_id_eq] : nil) %>
      <% if organization_type_param.present? %>
        <% options_for_organization_id = [['','']]+ActivistsCollaboration.organizations_by_type("Member"+organization_type_param).collect{ |o| [o.name, o.id] } %>
      <% else %>
        <% options_for_organization_id = [['','']] %>
      <% end %>
      <%= select 'activist', 'activists_collaborations_organization_id_eq', options_for_organization_id, :selected => organization_id_param %>
      <% content_for(:head){ javascript_tag "addAutocompleteInputCallback('activist_activists_collaborations_organization_id_eq', '#{autonomic_teams_for_search_path}', 'organization_id', 'activist_activists_collaborations_autonomic_teams_id_eq');" } %>
    </td>
  </tr>

  <tr class="list_style_0 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.autonomic_teams') %>:</label>
    </td>
    <td>
      <% autonomic_team_id_param  = (params[:activist] ? params[:activist][:activists_collaborations_autonomic_teams_id_eq] : nil) %>
      <% if organization_type_param == 'Autonomy' && !organization_id_param.blank? %>
        <% options_for_autonomic_team_id = [['','']]+Autonomy.find(organization_id_param).autonomic_teams.collect{|t| [t.name, t.id] } %>
      <% else %>
        <% options_for_autonomic_team_id = [['','']] %>
      <% end %>
      <%= select 'activist', 'activists_collaborations_autonomic_teams_id_eq', options_for_autonomic_team_id, :selected => autonomic_team_id_param %>
    </td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.collaboration_type') %>:</label><i class="help"><%= t("form.multiple_select_help").html_safe %></i>
    </td>
    <td>
      <% collaboration_type_param  = (params[:activist] ? params[:activist][:activists_collaborations_collaboration_type_in] : '') %>
      <%= select 'activist', 'activists_collaborations_collaboration_type_in', 
                 options_for_select(ActivistsCollaboration.collaboration_types.collect { |x| [t("activists_collaboration." + x),x] }, collaboration_type_param),
                 {}, { :multiple => true } %>
    </td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.join_at') %></label>
    </td>
    <td>
          Entre <%= text_field_tag "activist[activists_collaborations_join_at_gteq]", 
                                   (params[:activist] ? params[:activist][:activists_collaborations_join_at_gteq] : ''),
                                   :size => '8', :maxlength => 10
                %>
          <%= javascript_tag("$('#activist_activists_collaborations_join_at_gteq').datepicker({ yearRange: '1990:#{Date.today.year}' });") %>

          y <%= text_field_tag "activist[activists_collaborations_join_at_lteq]", 
                                   (params[:activist] ? params[:activist][:activists_collaborations_join_at_lteq] : ''),
                                   :size => '8', :maxlength => 10
                %>
          <%= javascript_tag("$('#activist_activists_collaborations_join_at_lteq').datepicker({ yearRange: '1990:#{Date.today.year}' });") %>
    </td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.leave_at') %></label>
    </td>
    <td>
          Entre <%= text_field_tag "activist[activists_collaborations_leave_at_gteq]", 
                                   (params[:activist] ? params[:activist][:activists_collaborations_leave_at_gteq] : ''),
                                   :size => '8', :maxlength => 10
                %>
          <%= javascript_tag("$('#activist_activists_collaborations_leave_at_gteq').datepicker({ yearRange: '1990:#{Date.today.year}' });") %>

          y <%= text_field_tag "activist[activists_collaborations_leave_at_lteq]", 
                                   (params[:activist] ? params[:activist][:activists_collaborations_leave_at_lteq] : ''),
                                   :size => '8', :maxlength => 10
                %>
          <%= javascript_tag("$('#activist_activists_collaborations_leave_at_lteq').datepicker({ yearRange: '1990:#{Date.today.year}' });") %>
    </td>
  </tr>

  <tr class="list_style_0 hideable" style="display: none;">
    <td><label><%= t('activerecord.attributes.activists_collaboration.responsibility_ids') %></label><i class="help"><%= t("form.multiple_checkbox_or_help") %></i></td>
    <td><% Responsibility.all.each do |responsibility| %>
      <div class="left small_margin small">
	<%= check_box_tag("activist[activists_collaborations_responsibilities_id_eq_any][]",
			  responsibility.id,
			  (params[:activist] && params[:activist]['activists_collaborations_responsibilities_id_eq_any'] && params[:activist]['activists_collaborations_responsibilities_id_eq_any'].include?(responsibility.id.to_s)),
        {:style => 'width: 20px' }) %> <%= responsibility.name %>
        
      </div>
    <% end %></td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td><label><%= t('activerecord.attributes.activists_collaboration.expertise_ids') %></label><i class="help"><%= t("form.multiple_checkbox_or_help") %></i></td>
    <td><% Expertise.all.sort_by{|e|[e.category, e.name]}.each do |expertise| %>
      <p class="left small_margin small">
	<%= check_box_tag("activist[activists_collaborations_expertises_id_eq_any][]",
			  expertise.id,
			  (params[:activist] && params[:activist]['activists_collaborations_expertises_id_eq_any'] && params[:activist]['activists_collaborations_expertises_id_eq_any'].include?(expertise.id.to_s))) %> <%= "#{expertise.category}: #{expertise.name}" %>
      </p>
    <% end %></td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.availability_id') %>:</label>
    </td>
    <td>
      <%= select("activist", "activists_collaborations_availability_id_eq",
                 Availability.all.collect {|a| [a.name,a.id] },
                 { :selected => (( params[:activist] && params[:activist]['activists_collaborations_availability_id_eq']) ? params[:activist]['activists_collaborations_availability_id_eq'].to_i : ''),
                                        :include_blank => true }) %>
    </td>
  </tr>

  <tr class="list_style_1 hideable" style="display: none;">
    <td>
      <label><%= t('activerecord.attributes.activists_collaboration.more_info') %>:</label>
    </td>
    <td>
      <%= text_area_tag("activist[activists_collaborations_more_info_eq]", ((params[:activist] && params[:activist]["activists_collaborations_more_info_eq"]) ? params[:activist]["activists_collaborations_more_info_eq"] : '')) %>

    </td>
  </tr>
</table>

app/views/search/_autonomic_teams_for_search.html.erb
<% options = (autonomy.nil? ? [] : autonomy.autonomic_teams.collect{|team|[team.name,team.id]} ) %>
<%= options_for_select options.prepend(['','']) %>

app/views/search/_campaignactions_filters.html.erb
<table class="table_list" >
  <tr class="important_row">
    <td colspan="2"><%= t('campaignaction.search.search_params') %></td>
  </tr>

  <tbody class="unhideable">

  <tr class="list_style_0">
    <td>
      <label><%= Gx.t_attr('campaignaction.organization_type') %>:</label>
    </td>
    <% organization_type_param  = (params[:campaignaction] and params[:campaignaction][:organization_type_eq]) ? params[:campaignaction][:organization_type_eq] : '' %>
    <% organization_type_values = [ [ Gx.t_attr("performance.choose_one_organization_type"), ""],
                                    [ Gx.t_attr('activists_collaboration.localorganization'), 'LocalOrganization'], 
                                    [ Gx.t_attr('activists_collaboration.autonomy'), 'Autonomy'] ] %>

    <td>
        <%= select 'campaignaction', 'organization_type_eq', organization_type_values, :selected => organization_type_param %>
        <% content_for(:head){ javascript_tag "addAutocompleteInputCallback('campaignaction_organization_type_eq', '#{organizations_for_search_path}', 'organization_type', 'campaignaction_organization_id_eq');" } %>
    </td>
  </tr>
  <tr class="list_style_1">
    <td>
      <label><%= Gx.t_attr('campaignaction.organization_id') %>:</label>
    </td>
      <% organization_id_param  = (params[:campaignaction] and params[:campaignaction][:organization_id_eq]) ? params[:campaignaction][:organization_id_eq] : nil %>
      <% if organization_type_param.present? %>
        <% organizations_for_campaignactions = [['','']]+Campaignaction.organizations_for(organization_type_param).collect{ |ao| [ao.name, ao.id] } %>
      <% else %>
        <% organizations_for_campaignactions = [ [ t("campaignaction.choose_one_organization_type"), ''] ] %>
      <% end %>
    <td><%= select 'campaignaction', 'organization_id_eq', organizations_for_campaignactions, :selected => organization_id_param %>
  </tr>

    <% Campaignaction.unhideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'campaignaction', :field_name => field_name } %>
    <% end %>

  </tbody>

  <%= render :partial => 'show_more_row' %>

  <tbody id="campaignaction_extra_fields" class="hideable" style="display: none;">
    <% Campaignaction.hideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'campaignaction', :field_name => field_name } %>
    <% end %>
  </tbody>

</table>

app/views/search/_hr_schools_filters.html.erb
<table class="table_list" >
  <tr class="important_row">
    <td colspan="2"><%= t('hr_school.search.search_params') %></td>
  </tr>

  <tbody class="unhideable">
    <% HrSchool.unhideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'hr_school', :field_name => field_name } %>
    <% end %>
  </tbody>

  <%= render :partial => 'show_more_row', :locals => { :onclick => "$('#hr_school_extra_fields').toggle()" } %>

  <tbody id="hr_school_extra_fields" class="hideable" style="display: none;">
    <% HrSchool.hideable_fields.each do |field_name| %>
      <%= render :partial => 'filters_field', :locals => { :klass => 'hr_school', :field_name => field_name } %>
    <% end %>
  <tr class="important_row">
    <td colspan="2"><%= Gx.t_attr('hr_school.sections.school_management') %></td>
  </tr>

  <tr class="list_style_0 school_management_only">
    <td><label><%= Gx.t_attr('hr_school.assigned_organization_type') %>:</label></td>
    <% assigned_organization_type_param  = (params[:hr_school] and params[:hr_school][:assigned_organization_type_eq]) ? sanitize(params[:hr_school][:assigned_organization_type_eq]) : '' %>
    <% assigned_organization_type_values = [ 
      [ Gx.t_attr("performance.choose_one_organization_type"), ""],
      [ Gx.t_attr('activists_collaboration.localorganization'), 'LocalOrganization'],
      [ Gx.t_attr('activists_collaboration.autonomy'), 'Autonomy'], 
      [ Gx.t_attr('activists_collaboration.se_team'), 'SeTeam'] ] %>
    <td>
      <%= select "hr_school", "assigned_organization_type_eq", assigned_organization_type_values, :selected => assigned_organization_type_param %>
      <% content_for(:head){ javascript_tag "addAutocompleteInputCallback('hr_school_assigned_organization_type_eq', '#{organizations_for_hr_schools_path}', 'assigned_organization_type', 'hr_school_assigned_organization_id_eq');" } %>
    </td>
  </tr>

  <tr class="list_style_1">
    <td>
      <label><%= Gx.t_attr('hr_school.assigned_organization_id') %>:</label>
    </td>
    <td>
      <% assigned_organization_id_param  = (params[:hr_school] and params[:hr_school][:assigned_organization_id_eq]) ? params[:hr_school][:assigned_organization_id_eq] : nil %>
      <% assigned_organization_id_values = HrSchool.organizations_for(assigned_organization_type_param).collect{|o|[o.full_name,o.id]} %>
      <%= select( 'hr_school', 'assigned_organization_id_eq', assigned_organization_id_values, :selected => assigned_organization_id_param) %>
    </td>
  </tr>

  <tr class="important_row">
    <td colspan="2"><%= Gx.t_attr('hr_school.sections.organization_managers') %></td>
  </tr>

  <tr class="list_style_0">
    <td>
      <label><%= Gx.t_attr('hr_school_organization_manager.organization_type') %>:</label>
    </td>
    <% organization_type_param  = (params[:hr_school] and params[:hr_school][:hr_school_organization_managers_organization_type_eq]) ? sanitize(params[:hr_school][:hr_school_organization_managers_organization_type_eq]) : '' %>
    <% organization_type_values = [ [ Gx.t_attr("performance.choose_one_organization_type"), ""],
                                    [ Gx.t_attr('activists_collaboration.localorganization'), 'LocalOrganization'], 
                                    [ Gx.t_attr('activists_collaboration.autonomy'), 'Autonomy'] ] %>
    <td>
      <%= select "hr_school", "hr_school_organization_managers_organization_type_eq", organization_type_values, :selected => organization_type_param, :include_blank => true %>
      <% content_for(:head){ javascript_tag "addAutocompleteInputCallback('hr_school_hr_school_organization_managers_organization_type_eq', '#{organizations_for_search_path}', 'organization_type', 'hr_school_hr_school_organization_managers_organization_id_eq');" } %>
    </td>
  </tr>
  <tr class="list_style_1">
    <td>
      <label><%= Gx.t_attr('hr_school_organization_manager.organization_id') %>:</label>
    </td>
    <td>
      <% organization_id_param  = (params[:hr_school] and params[:hr_school][:hr_school_organization_managers_organization_id_eq]) ? params[:hr_school][:hr_school_organization_managers_organization_id_eq] : nil %>
      <% organization_id_values = HrSchool.organizations_for(organization_type_param).collect{|o|[o.full_name,o.id]} %>
      <%= select 'hr_school', 'hr_school_organization_managers_organization_id_eq', assigned_organization_id_values, :selected => assigned_organization_id_param, :include_blank => true %>
    </td>
  </tr>

  </tbody>

</table>

app/views/search/_show_more_row.html.erb
<% defined?(onclick) ? nil : onclick = "$('.hideable').toggle();return false;" %>
  <tr class="show_more_row">
    <td colspan="2"> 
       <%= link_to_function t("search.show_hide_hideable_fields"), onclick.html_safe %>
    </td>
  </tr>

app/views/search/organizations_id_for_search.html.erb
<option value=""></option>
<% @organizations.each do |organization| %>
  <option value="<%= organization.id %>"><%= organization.name %></option>
<% end %>