config/routes.rb
AiVoluntariado::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :users do
    get :delete, :on => :member
    
    resources :performances do 
      get :delete, :on => :member
    end

    resources :organizations_trackings do
      get :delete, :on => :member
      get :destroy_all, :on => :collection
    end
      
  end

  resources :roles do
    get :delete, :on => :member
  end

  resources :performances do 
    get :delete, :on => :member
  end

  resource :site, :only => [:show,:edit,:update]

  match '/monitoring' => "monitoring#index", :as => :monitoring

  resources :activists do

    member do 
      get :delete
      get :leave
      get :clear
      get :rejoin
      get :admin_request
      put :send_admin_request
    end

    resources :activists_collaborations do 
      get :delete, :on => :member
    end

    resources :notes do
      get :delete, :on => :member
    end

  end

  resources :campaignactions do
    get :delete, :on => :member
  end

  resources :custom_actions do
    get :delete, :on => :member
  end

  resources :campaigns do
    get :delete, :on => :member
    get :show_info, :on => :collection
  end

  resources :hr_schools do
    get :delete, :on => :member
    resources :notes do 
      get :delete, :on => :member
    end
  end

  resources :mail_template_collections

  resources :provinces

  resources :talks do
    get :delete, :on => :member
  end

  resources :interesteds do
    get :delete, :on => :member
    get :to_activist, :on => :member
    get :prepare_pdf, :on => :member
    put :send_pdf, :on => :member
    get :prepare_mail, :on => :member
    put :send_mail, :on => :member

    resources :interested_communications, :path => :communications do 
      get :delete, :on => :member
      resources :notes do
        get :delete, :on => :member    
      end
    end

  end

  # ROUTES FOR ORGANIZATIONS

  resources :autonomies do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :autonomic_teams do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :committees do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  resources :countries do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
  end

  resources :local_organizations do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :se_teams do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  #ROUTES FOR EVENT RECORDS
  EventRecord.child_classes.prepend('EventRecord').each do |klass_name|
    resources klass_name.underscore.pluralize, :controller => 'event_records', :defaults => (klass_name != 'EventRecord' ? {:type => klass_name}:{}) do 
      get :delete, :on => :member    
      resources :notes do
        get :delete, :on => :member    
      end
    end
  end if EventRecord.table_exists?

  #ROUTES FOR ALERTS

  resources :alerts do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member    
    end
  end

  # Routes for AJAX requests
  match '/stages_for_performances'        => "performances#stages_for_performances", :as => :stages_for_performances
  match '/organizations_for_hr_schools'   => "hr_schools#organizations_for",         :as => :organizations_for_hr_schools
  match '/organizations_for_search'       => "search#organizations_for",             :as => :organizations_for_search
  match '/autonomic_teams_for_search'     => "search#autonomic_teams_for",           :as => :autonomic_teams_for_search
  match '/collaboration_types_for_search' => "search#collaboration_types_for",       :as => :collaboration_types_for_search
  match '/autonomic_teams_for_autonomy'   => "autonomies#autonomic_teams_for",       :as => :autonomic_teams_for_autonomy
  
  # Routes for auto_complete
  #TODO: simplify these routes
  match '/auto_complete/talks_as_options_for_interesteds' => 'talks#talks_as_options_for_interesteds', :as => :talks_as_options_for_interesteds_talks
  match '/auto_complete/talks_as_options_for_search'      => 'talks#talks_as_options_for_search',      :as => :talks_as_options_for_search_talks

#  match '/auto_complete/local_organizations_as_options_for_activists_collaborations/:local_organization_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_local_organization_activists_collaborations
#  match '/auto_complete/committees_as_options_for_activists_collaborations/:committee_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_committee_activists_collaborations
#  match '/auto_complete/se_teams_as_options_for_activists_collaborations/:se_team_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_se_team_activists_collaborations
#  match '/auto_complete/countries_as_options_for_activists_collaborations/:country_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_country_activists_collaborations
#  match '/auto_complete/autonomies_as_options_for_activists_collaborations/:autonomy_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_autonomy_activists_collaborations

  #PUBLIC ROUTES

  # HHRR schools: localized actions
  scope "(:locale)" do
    match '/form_hr_schools'   => 'public#new_hr_school',  :as => :form_hr_schools
    ["new_hr_school", "create_hr_school", "confirm_hr_school", "list_hr_schools"].each do |action_name|
      match "public/#{action_name}" => "public##{action_name}"
    end
  end

  # Interesteds: non-localized actions
  match '/form_voluntariado' => 'public#new_interested', :as => :form_voluntariado
  ["new_interested", "create_interested", "confirm_interested", "different_residence_country"].each do |action_name|
    match "public/#{action_name}" => "public##{action_name}"
  end

  # Ajax request for forms
  match '/provinces_for_cps'              => "public#provinces_for", :as => :provinces_for_cps
  match '/cities_for_province'            => "public#cities_for",    :as => :cities_for_province
  match '/city_for_cp'                    => "public#cities_for",    :as => :city_for_cp
  match '/cp_for_city'                    => "public#cp_for",        :as => :cp_for_city

  # Other static routes
  match '/gen_alerts'        => 'alerts#generate',  :as => :gen_alerts
  match '/search'            => 'search#index',     :as => :search
  match '/admin'             => 'admin#index',      :as => :admin

  root :to => "activists#index"

  # Note: This route will make all actions in every controller accessible via GET requests.
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Uncommment only for route testing purposes
#  match ':controller(/:action(/:id))(.:format)' 

end

app/models/autonomy.rb
class Autonomy < ActiveRecord::Base
  
  attr_accessible :name, :collaborations_enabled, :phone, :address, :cp, :province_id, :city, :email, :email_2, :fax, 
                  :customer_service_time, :meeting_weekday, :meeting_frequency, :meeting_hours, :meeting_venue, 
                  :postal_address, :postal_cp, :postal_province_id, :postal_city, 
                  :delivery_contact, :delivery_phone, :delivery_hours, :delivery_address, :delivery_cp, :delivery_province_id, :delivery_city,
                  :autonomic_team_ids

  include ActiveRecord::AIActiveRecord
  include ActiveRecord::AIOrganization
  include MailTemplateConsumer

  has_many :campaignactions, :as => :organization, :dependent => :destroy
  has_many :custom_actions, :as => :organization, :dependent => :destroy
  has_many :talks, :foreign_key => :organization_id, :conditions => "organization_type = 'Autonomy'", :dependent => :destroy
  has_many :autonomic_teams, :dependent => :destroy
  
  has_many :assigned_hr_schools, :as => :assigned_organization, :class_name => 'HrSchool', :dependent => :restrict
  has_many :hr_school_organization_managers, :as => :organization, :dependent => :destroy
  has_many :near_hr_schools, :through => :hr_school_organization_managers, :source => :hr_school, :class_name => 'HrSchool'

  def full_name; name; end

  def to_title;
    "#{ I18n.t("autonomy.abrev") }: #{ full_name }";
  end
  
#  def check_campaigns
#    if self.campaignactions.any?
#      self.errors.add :base, :has_campaignactions
#      return false
#    end
#  end

  #OPTIMIZE: Maybe this method should be in AIOrganization...
  def active_members_with_responsibility(responsibility_name)
    resp = Responsibility.find_by_name(responsibility_name) 
    managers = activists_collaborations.collect {|c| c.activist if (c.has_responsibility?(resp) && c.is_active && c.is_member) }.compact
  end

  # User can read autonomy if has access to one of its teams
  authorizing do |user, permission|
    if user.is_a?(User) and permission == :read
      matching_teams = user.agent_performances.collect{|p|p.stage if p.stage_type == 'AutonomicTeam'} & autonomic_teams
      return true if matching_teams.any?
    end
    nil 
  end
  
  # Overrides AIOrganization.can_choose to include autonomic teams
  scope :can_choose, lambda { |agent|
    conditions = "#{ self.name.tableize }.enabled = 1"
    if agent.is_a?(User) and not agent.has_any_permission_to(:read, self.name, :on => Site.current)
      can_read = agent.performances.select{|p|  p.stage_type == "#{ self.name }" }.map(&:stage_id) 
      can_read |= agent.performances.select{|p|  p.stage_type == "AutonomicTeam" }.map(&:stage).collect(&:autonomy_id)
      if can_read.any?
        conditions = '' "#{ self.name.tableize }.id IN(#{ can_read.join(',') })"
      else # ensure cant read
        conditions = " 1 != 1 "
      end
    end 
    {  :conditions => "#{ conditions }" }
  }

end

app/controllers/interesteds_controller.rb
require "erb"
include ERB::Util

class InterestedsController < ApplicationController
  include ActionController::AIController

  
  authorization_filter :create, :interested, :only => [ :new, :create ]
  authorization_filter :read,   :interested, :only => [ :show, :index ]
  authorization_filter :update, :interested, :only => [ :edit, :update]
  authorization_filter :destroy, :interested, :only => [ :delete, :destroy ]
  
  # Definitions for filters on index action
  def filters_for_index
    {
      :is_minor => [:is_minor, true],
      :has_pending_communication => [:has_pending_communication, true],
      :is_activist => [:is_activist, true],
      :with_talks => [:with_talks, true]
    }
  end

  # Default values for filters on index action
  def default_filters_for_index
    {}
  end

  def new
    @resource = Interested.new
    super
  end

  def prepare_mail
    resource
  end

  def prepare_pdf
    resource
  end

  def send_mail
    resource
    
    if params['mailto'].empty?
      flash[:error] = t('interested.no_email_for_sent')
      render :action => :prepare_mail
    else
      !@resource.is_minor? || @resource.minor_checked ? @resource.email_sent = true : nil
      unless @resource.save 
        flash[:error] = t('interested.fail_at_updated')
      else
        unless ApplicationMailer.contact_email(@resource, params).deliver
          flash[:error] = t('interested.fail_at_send_email')
        else
          flash[:notice] = t('interested.email_sent_success')
        end
      end
      redirect_to interesteds_path
    end
  end

  def send_pdf
    resource
    
    body = params['body']
    pdf_string = HtmlToPdf.generate_pdf_string(body)
    sending_success = pdf_string && send_data(pdf_string, :type => "application/pdf", :filename => "letter_#{ @resource.id }.pdf" , :disposition => 'attachment') 
    if sending_success
      !@resource.is_minor? || @resource.minor_checked ? @resource.letter_sent = true : nil
      unless @resource.save 
        flash[:error] = t('interested.fail_at_updated')
      else
        flash[:notice] = t('interested.letter_sent_success')
      end
    else
      error_string = (pdf_string.nil? ? t('interested.fail_at_pdf_generation') : t('interested.fail_at_pdf_sending') )
      redirect_to prepare_pdf_interested_path(@resource), :flash => { :error => error_string }
    end
  end

  def to_activist
    resource
    
    if @resource.is_minor? and not @resource.minor_checked
      flash[:error] = t('interested.cant_be_activist_due_age')
      redirect_to interesteds_path
    elsif request.get?
      if @resource.valid_to_migrate? and @resource.to_activist!
        redirect_to new_activist_activists_collaboration_path(@resource.activist)
      else
        if @resource.migrate_errors
          error_list = @resource.migrate_errors.full_messages
        else
          error_list = @resource.errors.full_messages
          error_list += @resource.activist.errors.full_messages if @resource.activist
        end
        flash[:error] = t('form.actions.not_created', :scope => 'activist' ) +  "<br>" + error_list.join("<br />")
        redirect_to edit_interested_path(@resource)
      end
    end
  end
end

app/helpers/interesteds_helper.rb
module InterestedsHelper

  def interested_collection_action_buttons
    ''.tap do |html|
        html << "<ul id='interested_communications_buttons' class='actions right'><li>"
        html << collection_action_button(Interested, 'communications', :wrapper_tag => '')
        html << "<ul>"
        html << collection_action_button(Interested, 'prepare_mail', :wrapper_tag => :li) #if current_user.has_any_permission_to(:create_email, :interesteds, :on => Site.current)
        html << collection_action_button(Interested, 'prepare_pdf', :wrapper_tag => :li) # if current_user.has_any_permission_to(:create_pdf,   :interesteds, :on => Site.current)
        html << collection_action_button(Interested, 'new_communication', :wrapper_tag => :li) # if current_user.has_any_permission_to(:update,   :interesteds, :on => Site.current)
        html << '</ul></li>'
        html << "</ul>"
        html << collection_action_button(Interested, 'to_activist') # if current_user.has_any_permission_to(:create, :activists, :on => Site.current) 
    end
  end

  def interested_show_action_buttons(interested)
    ''.tap do |html|
        if interested.activist.present?
          html << content_tag(:div, :class => "actions right"){link_to( t("form.buttons.show_activist"), interested.activist, :class => "action_show_activist with_icon")} if current_user.has_any_permission_to(:read, :activists, :on => Site.current) 
        else
          html << "<ul id='interested_communications_buttons' class='actions right'><li>"
          html << link_to( t("form.buttons.communications"), interested_interested_communications_path(interested), :class => "action_communications with_icon")
          html << "<ul>"
          html << object_action_button_to(interested, 'prepare_mail', :wrapper_tag => :li) if interested.authorize?(:update, :to => current_user)
          html << object_action_button_to(interested, 'prepare_pdf', :wrapper_tag => :li) if interested.authorize?(:update, :to => current_user)
          html << button_to_new_communication(interested) if interested.authorize?(:update, :to => current_user)
          html << '</ul></li>'
          html << "</ul>"
          html << object_action_button_to(interested, 'to_activist') if interested.authorize?(:update, :to => current_user)
      end
    end
  end

  def button_to_new_communication(interested)
    action = 'new_communication'
    new_communication = interested.communications.new
    interested.communications.delete new_communication
    content_tag :li, :class => "actions right" do
      link_to( t("form.buttons.#{action}"), new_polymorphic_url([ interested, new_communication ]), :class => "action_#{action} with_icon")
    end
  end

end

app/views/interesteds/_interested.html.erb
<%= gx_form_for(interested, { :disabled => true }) do |f| %>
  <%= render :partial => "form",  :object => f %>
<% end %>

app/views/interesteds/_list_body.html.erb
<% embedded ||= false %>
<% unless embedded %>
<%
    new_communication = interested.communications.new
    interested.communications.delete new_communication
%>
  <%= raw hidden_inputs_for(interested, count, { :hide => [ 'notes' ], 
                              :more => [ 
                                        :communications  => interested_interested_communications_path(interested),
                                        :to_activist  => to_activist_interested_path(interested),
                                        :prepare_mail => prepare_mail_interested_path(interested),
                                        :prepare_pdf  => prepare_pdf_interested_path(interested), 
                                        :new_communication  => new_polymorphic_url([ interested, new_communication ]) 
                                       ]}) %>
<% end %>

<td>
  <ul>
  <% if interested.is_minor?  %>
    <% if interested.minor_checked.nil? || !interested.minor_checked %>
      <li class="red"><%= Gx.t_attr('interested.is_minor') %></li>
      <li class="red"><%= t('interested.cant_be_activist_due_age') %></li>
    <% else %>
      <li><%= Gx.t_attr('interested.is_minor') %></li>
      <li><%= Gx.t_attr('interested.minor_checked') %></li>
    <% end %>
  <% end %>

    <%= interested.activist.present? ?  raw("<li>#{ link_to(t('interested.migrated'), interested.activist) }</li>") : ''  %>

    <% if interested.present? and interested.email_addresses.any? %>
      <li><%= interested.email_sent?       ?  t('interested.email_sent')                             : t('interested.email_not_sent') %></li>
    <% else %>
      <li><%= interested.letter_sent?      ?  t('interested.letter_sent')                            : t('interested.letter_not_sent') %></li>
    <% end %>

  </ul>
</td>
<td><%= link_to h(interested.full_name), interested %></td>
<td><%= link_to( h(interested.email), "mailto:#{interested.email}") %></td>

<td><%= h interested.phone %></td>

<% if interested.local_organization %>
  <td><%= link_to( h(interested.local_organization.full_name), local_organization_path(interested.local_organization) ) %></td>
<% else %>
  <td><%= "#{interested.local_organization_id }"%></td>
<% end %>

app/views/interesteds/_list_header.html.erb
<!-- <<<<<HIDE_CHECK_BOX-->
<% if embedded.nil? %>
  <th></th>
<% end %>
<!-- >>>>>HIDE_CHECK_BOX-->
<th><%= t("interested.status") %></th>
<th><%= Gx.t_attr("interested.first_name") %></th>
<th><%= Gx.t_attr("interested.email") %></th>
<th><%= Gx.t_attr("interested.phone") %></th>
<th><%= Gx.t_attr("interested.local_organization_id") %></th>

app/views/interesteds/prepare_mail.html.erb
<%= round_div_box do %>
  <h1>Enviando correo electrónico a <%= @resource.full_name %></h1>
<% end %>



<%= form_tag( send_mail_interested_path, :method => 'put' ) do  %>

  <%= round_div_box do %>
    <table>
    <tr>
      <td><%= label_tag( "mailto", Gx.t_attr("interested.mail.mailto") ) %></td>
      <td><%= text_field_tag( "mailto", @resource.email_addresses.join(','), :class => 'big' ) %></td>
    </tr>
    <tr>
      <td><%= label_tag( "subject", Gx.t_attr("interested.mail.subject") ) %></td>
      <td><%= text_field_tag( "subject", "Contacto desde Amnistía Internacional", :class => 'big' ) %></td>
    </tr>
    <tr>
      <td><%= label_tag( "body", Gx.t_attr("interested.mail.body") ) %></td>
      <td><%= text_area_tag( "body", @resource.contact_email_body(:email), :class => 'big' ) %></td>
      <script>new nicEditor({iconsPath : '/assets/nicEditorIcons.gif'}).panelInstance('body');</script>
    </tr>
    </table>
  <% end %>

  <%= round_div_box do %>
    <div class='center form_actions'>
      <%= submit_tag( Gx.t("form.buttons.send") ) %>
    </div>
  <% end %>

<% end %>

app/views/interesteds/prepare_pdf.html.erb
<%= round_div_box do %>
  <h1>Generando carta en PDF para <%= @resource.full_name %></h1>
<% end %>

<%= javascript_include_tag 'nicEdit' %>

<%= form_tag( send_pdf_interested_path, :method => 'put' ) do -%>

  <%= round_div_box do %>
  <TABLE>
  <TR>
    <TD><%= label_tag( "body", Gx.t_attr("interested.mail.body") ); %></TD>
    <td><%= text_area_tag( "body", @resource.contact_email_body(:pdf), :style => 'width: 700px;' ) %></td>
    <%= javascript_tag "new nicEditor({iconsPath : '/assets/nicEditorIcons.gif', buttonList: []}).panelInstance('body');" %>
  </TR>
  </TABLE>
  <% end %>

  <%= round_div_box do %>
  <div class='center form_actions'>
     <%= submit_tag( Gx.t("form.buttons.send") ); %>
  </div>
  <% end %>

<% end -%>