config/routes.rb
AiVoluntariado::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  resources :users do
    get :delete, :on => :member
    
    resources :performances do 
      get :delete, :on => :member
    end

    resources :organizations_trackings do
      get :delete, :on => :member
      get :destroy_all, :on => :collection
    end
      
  end

  resources :roles do
    get :delete, :on => :member
  end

  resources :performances do 
    get :delete, :on => :member
  end

  resource :site, :only => [:show,:edit,:update]

  match '/monitoring' => "monitoring#index", :as => :monitoring

  resources :activists do

    member do 
      get :delete
      get :leave
      get :clear
      get :rejoin
      get :admin_request
      put :send_admin_request
    end

    resources :activists_collaborations do 
      get :delete, :on => :member
    end

    resources :notes do
      get :delete, :on => :member
    end

  end

  resources :campaignactions do
    get :delete, :on => :member
  end

  resources :custom_actions do
    get :delete, :on => :member
  end

  resources :campaigns do
    get :delete, :on => :member
    get :show_info, :on => :collection
  end

  resources :hr_schools do
    get :delete, :on => :member
    resources :notes do 
      get :delete, :on => :member
    end
  end

  resources :mail_template_collections

  resources :provinces

  resources :talks do
    get :delete, :on => :member
  end

  resources :interesteds do
    get :delete, :on => :member
    get :to_activist, :on => :member
    get :prepare_pdf, :on => :member
    put :send_pdf, :on => :member
    get :prepare_mail, :on => :member
    put :send_mail, :on => :member

    resources :interested_communications, :path => :communications do 
      get :delete, :on => :member
      resources :notes do
        get :delete, :on => :member    
      end
    end

  end

  # ROUTES FOR ORGANIZATIONS

  resources :autonomies do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :autonomic_teams do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :committees do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  resources :countries do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
  end

  resources :local_organizations do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :talks do
      get :delete, :on => :member 
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
    resources :campaignactions do
      get :delete, :on => :member 
    end    
    resources :custom_actions do
      get :delete, :on => :member 
    end    
  end

  resources :se_teams do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member 
    end
    resources :activists_collaborations do
      get :delete, :on => :member 
      get :autocomplete_activist_search, :on => :collection
    end
    resources :organization_on_offs do
      get :delete, :on => :member 
    end
  end

  #ROUTES FOR EVENT RECORDS
  EventRecord.child_classes.prepend('EventRecord').each do |klass_name|
    resources klass_name.underscore.pluralize, :controller => 'event_records', :defaults => (klass_name != 'EventRecord' ? {:type => klass_name}:{}) do 
      get :delete, :on => :member    
      resources :notes do
        get :delete, :on => :member    
      end
    end
  end if EventRecord.table_exists?

  #ROUTES FOR ALERTS

  resources :alerts do
    get :delete, :on => :member    
    resources :notes do
      get :delete, :on => :member    
    end
  end

  # Routes for AJAX requests
  match '/stages_for_performances'        => "performances#stages_for_performances", :as => :stages_for_performances
  match '/organizations_for_hr_schools'   => "hr_schools#organizations_for",         :as => :organizations_for_hr_schools
  match '/organizations_for_search'       => "search#organizations_for",             :as => :organizations_for_search
  match '/autonomic_teams_for_search'     => "search#autonomic_teams_for",           :as => :autonomic_teams_for_search
  match '/collaboration_types_for_search' => "search#collaboration_types_for",       :as => :collaboration_types_for_search
  match '/autonomic_teams_for_autonomy'   => "autonomies#autonomic_teams_for",       :as => :autonomic_teams_for_autonomy
  
  # Routes for auto_complete
  #TODO: simplify these routes
  match '/auto_complete/talks_as_options_for_interesteds' => 'talks#talks_as_options_for_interesteds', :as => :talks_as_options_for_interesteds_talks
  match '/auto_complete/talks_as_options_for_search'      => 'talks#talks_as_options_for_search',      :as => :talks_as_options_for_search_talks

#  match '/auto_complete/local_organizations_as_options_for_activists_collaborations/:local_organization_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_local_organization_activists_collaborations
#  match '/auto_complete/committees_as_options_for_activists_collaborations/:committee_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_committee_activists_collaborations
#  match '/auto_complete/se_teams_as_options_for_activists_collaborations/:se_team_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_se_team_activists_collaborations
#  match '/auto_complete/countries_as_options_for_activists_collaborations/:country_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_country_activists_collaborations
#  match '/auto_complete/autonomies_as_options_for_activists_collaborations/:autonomy_id' => 'activists_collaborations#auto_complete_for_activist_search', :as => :auto_complete_for_activist_search_autonomy_activists_collaborations

  #PUBLIC ROUTES

  # HHRR schools: localized actions
  scope "(:locale)" do
    match '/form_hr_schools'   => 'public#new_hr_school',  :as => :form_hr_schools
    ["new_hr_school", "create_hr_school", "confirm_hr_school", "list_hr_schools"].each do |action_name|
      match "public/#{action_name}" => "public##{action_name}"
    end
  end

  # Interesteds: non-localized actions
  match '/form_voluntariado' => 'public#new_interested', :as => :form_voluntariado
  ["new_interested", "create_interested", "confirm_interested", "different_residence_country"].each do |action_name|
    match "public/#{action_name}" => "public##{action_name}"
  end

  # Ajax request for forms
  match '/provinces_for_cps'              => "public#provinces_for", :as => :provinces_for_cps
  match '/cities_for_province'            => "public#cities_for",    :as => :cities_for_province
  match '/city_for_cp'                    => "public#cities_for",    :as => :city_for_cp
  match '/cp_for_city'                    => "public#cp_for",        :as => :cp_for_city

  # Other static routes
  match '/gen_alerts'        => 'alerts#generate',  :as => :gen_alerts
  match '/search'            => 'search#index',     :as => :search
  match '/admin'             => 'admin#index',      :as => :admin

  root :to => "activists#index"

  # Note: This route will make all actions in every controller accessible via GET requests.
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Uncommment only for route testing purposes
#  match ':controller(/:action(/:id))(.:format)' 

end

app/controllers/activists_controller.rb
class ActivistsController < ApplicationController
  
  include ActionController::AIController

  before_filter        :check_empty_collaborations_for_activist, :only => [ :show ]

  authorization_filter :create,  :activist, :only => [ :new, :create ]
  authorization_filter :read,    :activist, :only => [ :show ]
  authorization_filter :update,  :activist, :only => [ :edit, :update, :admin_request, :send_admin_request]
  authorization_filter :destroy, :activist, :only => [ :delete, :destroy ]
  
  authorization_filter :leave,   :activist, :only => [ :rejoin, :leave ]
  authorization_filter :clear,   :activist, :only => [ :clear ]
  
  before_filter        :update_different_country_location, :only => [ :create, :update ]
  before_filter        :set_controller_only_validations, :only => [ :create, :update ]


  # Definitions for filters on index action
  def filters_for_index
    {
      :is_leave => [:is_leave, true],
      :with_related_collaborations => [:with_related_collaborations_on, current_agent]
    }
  end

  # Default values for filters on index action
  def default_filters_for_index
    {
      :with_related_collaborations => true
    }
  end

  def admin_request
  end

  def send_admin_request
    resource
    if params['action'].empty?
      flash[:error] = t('activist.admin_request.no_action')
      redirect_to activist_path(@resource)
    else
      unless ApplicationMailer.activist_admin_request(@resource, current_user, params).deliver
        flash[:error] = t('activist.admin_request.fail_at_send')
      else
        flash[:notice] = t('activist.admin_request.sent_success')
      end
      redirect_to activist_path(@resource)
    end
  end

  def leave
    if activist.leave_at.nil?
      redirect_to url_for(:action => "edit", :section => "leave" )
    else
      redirect_to url_for(:action => "edit", :section => "leave", :show_clear => true )
    end
  end
  
  def clear
    set_resource
    @activist.clear_sensitive_data
    unless @activist.save(:validate => false)
      flash[:error] = @activist.errors.to_xml
    end
    redirect_to url_for(:action => "show")
  end

  def rejoin
    set_resource
    @activist.rejoin
    unless activist.save
      flash[:error] = @activist.errors.to_xml
    end
    redirect_to url_for(:action => "show")
  end
  
  def update
    if params[:activist_leave].present?
      if params[:activist]['leave_at(1i)'].empty? ||
          params[:activist]['leave_at(2i)'].empty? ||
          params[:activist]['leave_at(3i)'].empty?
        flash[:error] = Gx.t_error("activist.base.missing_leave_at")
        redirect_to url_for(:action => "edit",  :section => "leave" )
      elsif @resource.activists_collaborations.active_status.any?
        flash[:error] = Gx.t_error("activist.base.still_active_collaborations")
        redirect_to url_for(:action => "edit",  :section => "leave" )
      else
        resource
        if params[:clear_activist] and @resource.authorize?(:clear, :to => current_agent)
          @resource.clear_sensitive_data
        end
        respond_to do |format|
          format.html {
            if @resource.save(:validate => false)
              flash[:success] = t(:updated, :scope => @resource.class.to_s.underscore)
              redirect_to :action => :show, :referer => params[:referer]
            else
              flash[:error] = @resource.errors.inspect
              redirect_to url_for(:action => "edit",  :section => "leave" )
            end
          }
        end
      end
      return
    else
      super
    end
  end

  private

  def check_empty_collaborations_for_activist

    return if !Activist.exists?(params[:id])

    activist = Activist.find(params[:id])
    if activist.activists_collaborations.empty? && activist.leave_at.nil? && 
         current_user.has_any_permission_to(:create, :activists_collaboration) && !activist.authorizes?(:read, :to => current_user)
      render :action => 'activist_without_collaborations'
    end
  end

  def set_controller_only_validations
    @resource.must_check_unlinked_interested = true
  end

  def update_different_country_location
    if params[:different_residence_country]
      @activist.city        = params[:city_different_country]
      @activist.cp          = params[:city_different_country]
      @activist.province_id = 0
    end
  end

end

app/helpers/activists_helper.rb
module ActivistsHelper
  
  def collaboration_row(activist, collaboration)
    i18n_key = collaboration.is_member ? "member_collaborations_for_activist" : "other_collaborations_for_activist" 
    text = t( "activists_collaboration.texts.#{ i18n_key }", 
              :collaboration_type => link_to_if( collaboration.authorize?(:read, :to => current_agent), h(collaboration.kind), activist_activists_collaboration_path(collaboration.activist, collaboration) ),
              :organization       => link_to(h(collaboration.organization.name), collaboration_organization_path(collaboration)),
              :join_at            => localize(collaboration.join_at.to_date),
              :responsibility     => collaboration.h_responsibilities )
    collaboration.is_leave ? content_tag(:strike, text.html_safe) : text.html_safe
  end
end

app/views/activists/_activist.html.erb
<% if params[:section] %>

  <%= gx_form_for(activist, { :disabled => true }) do |f| %>
    <%= render :partial => "form",  :object => f, :locals => { :section => params[:section] } %>
  <% end %>

<% else %>

  <% if activist.has_no_active_collaborations and activist.leave_at.nil? %>
    <div class="background_soft_red big_padding font_plus_three">
      <%= raw t('activist.leave_status_text', :time_to_remove => activist.time_to_leave) %>
    </div>
  <% end %>


  <%= summary_view do %>

    <tr>
      <%= summary_section(:id => 'personal_data', :title => Gx.t_attr("activist.sections.data"))  do  %>
  
      <div class="actions">
          <%= summary_action(:update, edit_activist_path(activist, :section => "section_data"), { :to     => :edit, :object => activist }) %>
          <%= summary_action(:read,   activist_path(activist,      :section => "section_data"), { :to     => :show, :object => activist }) %>
        </div>

        <% if activist.nif.present? %>
          <p><%= summary_label activist.document_type %>: <%= summary_field activist.nif %></p>
        <% end %>

        <% [ 'address', 'email', 'phone', 'mobile_phone' ].each do |field| %>
          <p><%= summary_label Gx.t_attr("activist.#{ field }") %>: <%= summary_field activist.send(field) %></p>

        <% end %>
      <% end %>

      <%= summary_section(:id => 'skills_hobbies', :title => Gx.t_attr("activist.sections.skills_hobbies"))  do  %>

        <div class="actions">
          <%= summary_action(:update, edit_activist_path(activist, :section => "section_skills_hobbies"), { :to     => :edit, :object => activist }) %>
          <%= summary_action(:read,   activist_path(activist,      :section => "section_skills_hobbies"), { :to     => :show, :object => activist }) %>
        </div>

        <% [ 'languages', 'skills', 'hobbies' ].each do |relation| %>
          <% relation_ids = "#{ relation.singularize }_ids" %>
          <p><%= summary_label Gx.t_attr("activist.#{ relation_ids }") %>: <%= summary_field activist.send(relation).collect{ |o| o.name }.join(", ") %></p>
        <% end %>

      <% end %>
    </tr>


    <tr>

      <%= summary_section(:id => 'organizations_collab', :colspan => 2, :title => Gx.t_attr("activist.sections.collab_organizations"))  do  %>

        <div class="actions">
          <% new_collaboration = activist.activists_collaborations.new %>
          <% activist.activists_collaborations.delete new_collaboration %>
          <%= summary_action(:create, new_activist_activists_collaboration_path(activist), { :object => new_collaboration }) %>
          <%= summary_action(:read, activist_activists_collaborations_path(activist),    { :to => :edit, :object => new_collaboration }) %>
          <%= summary_action(:read, activist_activists_collaborations_path(activist),    { :to => :show, :object => new_collaboration }) %>
        </div>

        <% activist_collaborations = activist.activists_collaborations %>
        <% if activist_collaborations.empty? %>
          <h4 class="none">FIXME</h4>
        <% else %>

          <ul>
            <% activist_collaborations.each do |collaboration| %>
              <li><%= collaboration_row(activist, collaboration) %></li>
            <% end %>
          </ul>


        <% end %>
      <% end %>
    </tr>

    <tr>

      <%= summary_section(:id => 'activist_status_changes', :colspan => 2, :title => "#{Gx.t_attr("activist.sections.status_changes")}")  do  %>

        <% activist.activist_status_changes.each do |change| %>
          <% if  change.authorize?(:read, :to => current_agent) %>
            <p>
              <%= raw t "activist_status_change.texts.for_activist",
                    :date               => localize(change.date.to_date),
                    :status_change_name => change.activist_status.name,
                    :collaboration_type => link_to( h(change.activists_collaboration.kind), polymorphic_path(change.activists_collaboration)),
                    :organization       => link_to( h(change.activists_collaboration.organization_name), polymorphic_path(change.activists_collaboration.organization)) %>
            </p>

          <% end %>
        <% end %>
      <% end %>
    </tr>

    <% if activist.authorize?(:update, :to => current_user) %>
      <%= summary_notes_section_for(activist) %>
    <% end %>

  <% end %>
<% end %>

app/views/activists/_list_body.html.erb
<% readable_obj = controller.authorized?(:read, activist) %>
  <%= raw hidden_inputs_for(activist, count, {:more => [ :leave => leave_activist_url(activist), :admin_request => admin_request_activist_url(activist)] }) %>

  <td>
    <%= raw '<strike>' if activist.leave_at.present? %>
    <%= link_to_if readable_obj, h(activist.second_first_name), activist %>
    <%= raw '</strike>' if activist.leave_at.present? %>
  </td>

  <td>
    <% last_collaboration_type = nil %>
    <ul>
    <% activist.activists_collaborations_by_type.each do |collaboration_type, collaborations| %>
      <% collaboration_type ||= 'none' %>

      <% unless last_collaboration_type.eql?(collaboration_type) %>
          <%= t("activists_collaboration.#{ collaboration_type }") %>: 
      <% end %>
      <% last_collaboration_type = collaboration_type %>

      <% collaborations.each do |collaboration| %>
        <%= raw '<strike>' if collaboration.is_leave %>
          <li style="list-style-type: none;">
            <%= raw display_activist_collaborations_marks(collaboration) %>
            <%= link_to_if controller.authorized?(:read, collaboration.organization), h(collaboration.organization_name), polymorphic_path(collaboration.organization) %>
          </li> 
        <%= raw '</strike>' if collaboration.is_leave %>
      <% end %>
    <% end %>
    </ul>
  </td>

  <td><%= readable_obj ? mail_to(h(activist.email), activist.email) : '---' %></td>

  <td><%= readable_obj ? h(activist.phone) : '---' %></td>

  <td>
    <% if readable_obj %>
      <%= link_to I18n.t("form.buttons.notes"), activist_path(activist, :anchor => 'activist_section_notes') %>
    <% else %>
      <%= link_to I18n.t("form.buttons.add_collaboration"), new_activist_activists_collaboration_path(activist) if !activist.leave_at.present? %>
    <% end %>

  </td>

app/views/activists/_list_header.html.erb
<% if embedded.nil? %>
  <th></th>
<% end %>

<th><%= Gx.t_attr("activist.first_name") %></th>
<th><%= t("activist.member_of") %></th>
<th><%= Gx.t_attr("activist.email") %></th>
<th><%= Gx.t_attr("activist.phone") %></th>
<th></th>

app/views/activists/activist_without_collaborations.html.erb
    <div class="background_soft_red big_padding font_plus_three">
      <%= raw t('activist.leave_status_text', :time_to_remove => activist.time_to_leave) %>

    </div>

    <div style="clear:both"></div>
    <p style="margin: 20px; text-align:center;"><span style="padding: 10px; border: 1px solid; background-color:#FBFBFB; font-size:2.0em; ">
      <%= link_to I18n.t("form.buttons.add_collaboration"), new_activist_activists_collaboration_path(activist) if !activist.leave_at.present? %>
    </span></p>

app/views/activists/admin_request.html.erb
<%= gx_form_for( [:send_admin_request, @resource] ) do |form| %>

  <%= round_div_box do %>
    <div class="right form_actions">
      <% referer = request.params[:referer] || request.referer %>
      <%= hidden_field_tag 'referer', referer %>
      <input type="hidden" name="referer" value='<%=referer%>'></input>
      <%= button_to_function(I18n.t("form.buttons.back"), "document.location = '#{ referer }'", :class => 'action_cancel' ) %>
      <%= form.submit( I18n.t("form.buttons.send"), :class => 'action_apply', :name => 'commit', :confirm => t("activist.admin_request.confirm_request", :action => t("activist.admin_request.actions.leave")) ) if !form.object.leave_at.present? %>
    </div>
    <h1><%= t("activist.admin_request.title_html", :obj => link_to(@resource.full_name, @resource)) %></h1>
  <% end %>

  <h2><%= t 'activist.admin_request.form_info_html' %></h2>
  <% if form.object.leave_at.present? %>
    <p> <b> <%= t("activist.admin_request.clear_label_html") %> </b>
      <ul>
        <% ['rejoin','clear','delete'].each do |op| %>
          <li><%= link_to( raw(t "activist.admin_request.actions.#{op}"), send_admin_request_activist_path(activist.id, :operation => op), :method => 'put', :confirm => t("activist.admin_request.confirm_request", :action => t("activist.admin_request.actions.#{op}")) ) %></li>
        <% end %>
      </ul>
    </p>

  <% else %>
  <table id="<%= params[:action] %>_activist_form" class="table_form">
    <tr class="form_section">
      <td><%= form.label "sections.leave" %></td>
      <td></td>
    </tr>

    <input type="hidden" name="operation" value="leave"></input>

    <tr class="list_style_0">
      <td><%= form.label 'clear' %></td>
      <td><%= check_box_tag 'leave_op[clear]', 'SI' %> <%= t('activist.clear_checkbox') %></td>
    </tr>

    <tr class="list_style_1">
      <td><%= form.label_required 'leave_at' %></td>
      <td><%= text_field_tag 'leave_op[leave_at]', I18n.localize(Date.today, :format => '%d-%m-%Y'), { :size => 8, :maxlength => 10, :readonly => true } %></td>
      <%= javascript_tag("$('#leave_op_leave_at').datepicker();") %>
    </tr>

    <tr class="list_style_0">
      <td><%= form.label 'leave_reason_id' %></td>
      <td><%= select_tag 'leave_op[leave_reason_id]', options_for_select(LeaveReason.all.collect(&:name)), { :include_blank => true } %></td>
    </tr>

    <tr class="list_style_1">
      <td><%= form.label :leave_more_info %></td>
      <td><%= text_area_tag 'leave_op[leave_more_info]' %></td>
    </tr>
  </table>
  <% end %>


  <%= round_div_box do %>
    <div class='center form_actions'>
      <%= form.submit( I18n.t("form.buttons.send"), :class => 'action_apply', :name => 'commit', :confirm => t("activist.admin_request.confirm_request", :action => t("activist.admin_request.actions.leave")) ) if !form.object.leave_at.present? %>
    </div>
  <% end %>

<% end %>